### User Defined Parameter Values

In [2]:
import pybamm


In [3]:
model = pybamm.lithium_ion.DFN()
parameter_values = pybamm.ParameterValues(chemistry=pybamm.parameter_sets.Chen2020)
parameter_values

{'1 + dlnf/dlnc': 1.0,
 'Ambient temperature [K]': 298.15,
 'Bulk solvent concentration [mol.m-3]': 2636.0,
 'Cation transference number': 0.2594,
 'Cell cooling surface area [m2]': 0.0053100000000000005,
 'Cell volume [m3]': 2.42e-05,
 'Current function [A]': 5.0,
 'EC diffusivity [m2.s-1]': 2e-18,
 'EC initial concentration in electrolyte [mol.m-3]': 4541.0,
 'Electrode height [m]': 0.065,
 'Electrode width [m]': 1.58,
 'Electrolyte conductivity [S.m-1]': <function electrolyte_conductivity_Nyman2008 at 0x0000021E84FBECA0>,
 'Electrolyte diffusivity [m2.s-1]': <function electrolyte_diffusivity_Nyman2008 at 0x0000021E84FBEDC0>,
 'Initial concentration in electrolyte [mol.m-3]': 1000.0,
 'Initial concentration in negative electrode [mol.m-3]': 29866.0,
 'Initial concentration in positive electrode [mol.m-3]': 17038.0,
 'Initial inner SEI thickness [m]': 2.5e-09,
 'Initial outer SEI thickness [m]': 2.5e-09,
 'Initial temperature [K]': 298.15,
 'Inner SEI electron conductivity [S.m-1]': 8

In [5]:
import numpy as np

def my_current(t):
    return pybamm.sin(2 * np.pi * t / 60)

parameter_values["Current function [A]"] = my_current
parameter_values

{'1 + dlnf/dlnc': 1.0,
 'Ambient temperature [K]': 298.15,
 'Bulk solvent concentration [mol.m-3]': 2636.0,
 'Cation transference number': 0.2594,
 'Cell cooling surface area [m2]': 0.0053100000000000005,
 'Cell volume [m3]': 2.42e-05,
 'Current function [A]': <function my_current at 0x0000021E84FBEF70>,
 'EC diffusivity [m2.s-1]': 2e-18,
 'EC initial concentration in electrolyte [mol.m-3]': 4541.0,
 'Electrode height [m]': 0.065,
 'Electrode width [m]': 1.58,
 'Electrolyte conductivity [S.m-1]': <function electrolyte_conductivity_Nyman2008 at 0x0000021E84FBECA0>,
 'Electrolyte diffusivity [m2.s-1]': <function electrolyte_diffusivity_Nyman2008 at 0x0000021E84FBEDC0>,
 'Initial concentration in electrolyte [mol.m-3]': 1000.0,
 'Initial concentration in negative electrode [mol.m-3]': 29866.0,
 'Initial concentration in positive electrode [mol.m-3]': 17038.0,
 'Initial inner SEI thickness [m]': 2.5e-09,
 'Initial outer SEI thickness [m]': 2.5e-09,
 'Initial temperature [K]': 298.15,
 'Inn

In [9]:
model = pybamm.lithium_ion.SPMe()
sim = pybamm.Simulation(model, parameter_values=parameter_values)
t_eval = np.arange(5,121, 1)
sim.solve(t_eval=t_eval)
sim.plot(["Current [A]"])

interactive(children=(FloatSlider(value=5.0, description='t', max=120.0, min=5.0, step=1.2), Output()), _dom_c…

### Saving output

In [13]:
sol = sim.solution
sol

In [15]:
t = sol["Time [s]"]
V = sol["Terminal voltage [V]"]


In [16]:
V.entries

array([4.15775653, 4.15323414, 4.14901454, 4.14513254, 4.14161677,
       4.13849037, 4.13577224, 4.13347817, 4.13162154, 4.13021383,
       4.12926499, 4.12878359, 4.12877672, 4.12925003, 4.1302071 ,
       4.13164936, 4.13357513, 4.13597907, 4.13885097, 4.14217465,
       4.14592651, 4.15007431, 4.15457605, 4.1593796 , 4.16442323,
       4.16963731, 4.17494713, 4.18027651, 4.18555134, 4.19070288,
       4.19566955, 4.20039822, 4.20484363, 4.20896821, 4.21274023,
       4.21613339, 4.21912485, 4.22169525, 4.22382696, 4.22550479,
       4.22671445, 4.22744373, 4.22768118, 4.22741824, 4.22664721,
       4.2253627 , 4.2235632 , 4.22125187, 4.21843658, 4.21513324,
       4.2113665 , 4.20717153, 4.20259528, 4.19769754, 4.19254876,
       4.1872291 , 4.18182356, 4.17641758, 4.17109252, 4.16592186,
       4.16096928, 4.15628783, 4.15192065, 4.14790249, 4.14426077,
       4.14101781, 4.13819166, 4.13579728, 4.13384747, 4.1323531 ,
       4.13132365, 4.13076726, 4.13069065, 4.13109905, 4.13199

In [17]:
t.entries

array([  5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.,  13.,  14.,  15.,
        16.,  17.,  18.,  19.,  20.,  21.,  22.,  23.,  24.,  25.,  26.,
        27.,  28.,  29.,  30.,  31.,  32.,  33.,  34.,  35.,  36.,  37.,
        38.,  39.,  40.,  41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,
        49.,  50.,  51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,
        60.,  61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.,
        71.,  72.,  73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.,  81.,
        82.,  83.,  84.,  85.,  86.,  87.,  88.,  89.,  90.,  91.,  92.,
        93.,  94.,  95.,  96.,  97.,  98.,  99., 100., 101., 102., 103.,
       104., 105., 106., 107., 108., 109., 110., 111., 112., 113., 114.,
       115., 116., 117., 118., 119., 120.])

In [18]:
V([20])  # times in seconds

array([4.13164936])

In [19]:
sim.plot()

interactive(children=(FloatSlider(value=5.0, description='t', max=120.0, min=5.0, step=1.2), Output()), _dom_c…

In [20]:
sol.save_data("Managing_Simulation_Outputs.csv", ["Current [A]", "Terminal voltage [V]"], to_format="csv")

### Model Options

In [14]:
options = {"thermal": "x-full"}
model = pybamm.lithium_ion.SPMe(options=options) # loading in options

parameter_values = model.default_parameter_values
parameter_values["Current function [A]"] = 3

sim = pybamm.Simulation(model, parameter_values=parameter_values)
sim.solve([0, 3600])

In [15]:
sim.plot(["Cell temperature [K]", "Total heating [W.m-3]", "Current [A]", "Terminal voltage [V]"])

interactive(children=(FloatSlider(value=0.0, description='t', max=807.116679131544, step=8.07116679131544), Ou…